name: Telegram Username Checker

on:
  schedule:
    # Run every day at 12:00 UTC
    - cron: '0 12 * * *'
  workflow_dispatch:
    # Allow manual trigger

jobs:
  check-usernames:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Run username checker
      run: |
        python telebot.py
        
    - name: Check if results files exist
      run: |
        ls -la *.txt *.json || echo "No result files found"
        
    - name: Commit and push results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update username check results - $(date '+%Y-%m-%d %H:%M:%S')"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}